### ISSUE TITLE
wifi怎么弄的

### ISSUE THREAD

**Issue by gas0324** [KusStar/Hasee-u45s1-Hackintosh#1]
我的是蓝牙能用，wifi不能用，目前不能睡眠

**Comment by KusStar** [comment]
[itlwm](https://github.com/zxystd/itlwm) + [HeliPort](https://github.com/zxystd/HeliPort)

**Comment by gas0324** [comment]
借用你的efi成功驱动了无线，不过我把驱动放到我的efi里就不行
还有，请问HeliPort这个是怎么使用的

**Comment by gas0324** [comment]
另外想请问你的触摸板连续操作五次，第五次是不是没有响应？

**Comment by KusStar** [comment]
我的不会这样

**Comment by gas0324** [comment]
有没有兴趣看一下我的efi，留个qq？

**Comment by KusStar** [comment]
> 借用你的efi成功驱动了无线，不过我把驱动放到我的efi里就不行
> 还有，请问HeliPort这个是怎么使用的

HeliPort 是这个驱动的配套客户端，和系统自带的WiFi管理基本一致，用于连接WiFi，需要自己编译

**Comment by gas0324** [comment]
> > 借用你的efi成功驱动了无线，不过我把驱动放到我的efi里就不行
> > 还有，请问HeliPort这个是怎么使用的
> 
> HeliPort 是这个驱动的配套客户端，和系统自带的WiFi管理基本一致，用于连接WiFi，需要自己编译

在群里找到一个编译好的

**Comment by gas0324** [comment]
另外咨询一下，你的插电源开机内置键盘可以使用吗？

**Comment by KusStar** [comment]
> 另外咨询一下，你的插电源开机内置键盘可以使用吗？

可以

**Comment by gas0324** [comment]
> > 另外咨询一下，你的插电源开机内置键盘可以使用吗？
> 
> 可以

你有没有遇到过插外置电源无法使用笔记本键盘的情况，知道怎么处理吗？我的一直无反应，拔掉电源开机就可以

**Comment by gas0324** [comment]
可以告诉我你的 USBInjectAll.kext 怎么弄的吗？我用你的这个驱动可以，我的qq是418026308，希望加个好友
