### ISSUE TITLE
去掉-v或者更新USBInjectAll.kext后接入电源开机无法识别内置键盘

### ISSUE THREAD

**Issue by gas0324** [KusStar/Hasee-u45s1-Hackintosh#2]
后来有更新吗？

**Comment by KusStar** [comment]
https://github.com/RehabMan/OS-X-USB-Inject-All
https://www.tonymacx86.com/threads/guide-creating-a-custom-ssdt-for-usbinjectall-kext.211311/

需要自行定制 SSDT

**Comment by gas0324** [comment]
求更新efi

**Comment by gas0324** [comment]
希望一直维护

**Comment by KusStar** [comment]
我用着没什么问题啊（目前在用 10.15.5），也没有什么需要维护的内容，凑合着用吧
